apiVersion: v1
kind: Secret
metadata:
  name: kicktipp-bot-secrets
  namespace: kicktipp-bot
type: Opaque
data:
  # required environment variables
  KICKTIPP_EMAIL: base-64-encoded-value
  KICKTIPP_PASSWORD: base-64-encoded-value
  KICKTIPP_NAME_OF_COMPETITION: base-64-encoded-value
  # optional environment variables
  ZAPIER_URL: base-64-encoded-value
  NTFY_URL: base-64-encoded-value
  NTFY_USERNAME: base-64-encoded-value
  NTFY_PASSWORD: base-64-encoded-value
  WEBHOOK_URL: base-64-encoded-value
